### ISSUE TITLE
void* -.-"

### ISSUE THREAD

**Issue by paoli7612** [davidemesso/LinkedListC#1]
https://github.com/davidemesso/LinkedListC/blob/fbf92d0b1f582bdbf0a2226a0d81d05f22b86d16/LinkedList.c#L12

**Comment by davidemesso** [comment]
> https://github.com/davidemesso/LinkedListC/blob/fbf92d0b1f582bdbf0a2226a0d81d05f22b86d16/LinkedList.c#L12

VoId StAr è Un Po StRaNo
